### ISSUE TITLE
Add CORS support to IIIF website infrastructure

### ISSUE THREAD

**Issue by mejackreed** [IIIF/website#318]
Related to https://github.com/IIIF/cookbook-recipes/issues/114

In prototyping IIIF Image v3 for Leaflet-IIIF and using https://iiif.io/api/image/3.0/example/reference/67352ccc-d1b0-11e1-89ae-279075081939/info.json .. it would be great to have CORS enabled for the IIIF site so we could use this as a client side image server.

**Comment by glenrobson** [comment]
Looks like there are two headers but probably need to have the correct case:

```
access-control-allow-origin: *
access-control-allow-origin: *
```

**Comment by mejackreed** [comment]
I think we need:

```
Access-Control-Allow-Origin: *
```

**Comment by glenrobson** [comment]
Looks like its a problem with multiple headers rather than the case. This works:

http://mejackreed.github.io/Leaflet-IIIF/examples/?url=http://image-api.iiif.io/api/image/2.0/example/reference/67352ccc-d1b0-11e1-89ae-279075081939/info.json

which has:

``` Access-control-allow-origin: * ```

but this doesn't:

http://mejackreed.github.io/Leaflet-IIIF/examples/?url=https://iiif.io/api/image/2.0/example/reference/67352ccc-d1b0-11e1-89ae-279075081939/info.json

**Comment by glenrobson** [comment]
Should now be fixed.

**Comment by mejackreed** [comment]
++ Thanks @glenrobson
