### ISSUE TITLE
Typo on "How it Works" page

### ISSUE THREAD

**Issue by regisrob** [IIIF/website#544]
Subtitle has a typo: "A plain-langauge guide to how the APIs work." 
https://iiif.io/get-started/how-iiif-works/

**Comment by hadro** [comment]
Thank you for the sharp eyes!

Though I think this must be a cache issue or something else, since Julien pointed out the same typo which was fixed up via https://github.com/IIIF/website/pull/528...

Does a hard refresh show you the fix, a la the screenshot below?

![image](https://user-images.githubusercontent.com/81478/142795382-ff390b0e-ba39-490e-8ba4-e0444f1d3877.png)

**Comment by regisrob** [comment]
The problem seems to be fixed now, even though I first had a strange behaviour with the hard refresh both in Chrome and FF: when I opened that page in a new tab I had the correct version (without the typo and with the background image), but after making a hard refresh I had the old version once again (with the typo and without background image) :man_shrugging:

**Comment by hadro** [comment]
I believe this is all fixed now, and also Glen fixed the cache setting so that changes actually propagate -- thanks!
